# Generated by Django 5.1.2 on 2025-02-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.table'),
        ),
    ]
