# Generated by Django 5.1.2 on 2024-12-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_catagory_task_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal')], max_length=255),
        ),
    ]
