# Generated by Django 5.1.2 on 2024-12-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_alter_catagory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Catagory',
            new_name='catagory',
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
