# Generated by Django 5.1.2 on 2025-01-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_remove_task_catagory_remove_task_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='reservation_date',
        ),
    ]
