# Generated by Django 5.1.2 on 2025-01-30 13:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_rename_due_date_task_reservation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved')], default='Available', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.datetime(2025, 1, 30, 13, 13, 53, 291453, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Task.table'),
        ),
    ]
