# Generated by Django 5.1.2 on 2025-02-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0014_user_is_admin_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('reservation_date', models.DateTimeField()),
                ('status', models.CharField(default='Available', max_length=50)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Task.table')),
            ],
        ),
    ]
