# Generated by Django 5.1.2 on 2025-02-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0015_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
